### ISSUE TITLE
Uplift?

### ISSUE THREAD

**Issue by ghost** [OneIdentity/IdentityManager.CyberArk#1]
Is there any plan to uplift the source files to suit a v9+ solution? (Specifically 9.0 LTS CU3)

Getting some attribute errors with importing the projshell (done by someone else, I'd expect them to be competent enough to follow the docx proceedure).

**Comment by ghost** [comment]
Issue raised in main issue tracking register

**Comment by ghost** [comment]
Despite README clearly stating and linking to Docker, issue was closed - https://github.com/OneIdentity/IdentityManager.Dockerfiles/issues/3

**Comment by MarkusWeiss-Ehlers** [comment]
The README states that issues should be posted in the issues section of the repository. This is common with GitHub repositories and nothing special just for OneIdentity.  Unfortunately, the links behind the text _One Identity GitHub issues_ and One Identity GitHub project_ were wrong. I've corrected this.

So, please post any issue you have with a repository in the Issues section of the same repository unless noted otherwise. Thank you.

**Comment by ghost** [comment]
So, is there a plan to uplift this repository or not? It hasn't been touched in 2 years.

**Comment by ghost** [comment]
Well, its abundantly clear that One Identity will not support any CyberArk integration. This will feed back into the current product review.
